### ISSUE TITLE
テストが死ぬ事象が発生(再現性低)

### ISSUE THREAD

**Issue by RussianBlue25** [RussianBlue25/kat#13]
@2da-tuba ちょっとみとくれ

**Comment by RussianBlue25** [comment]
4つ目のテストでこけている。手元で試したところ問題なかった。GitHub Actionsが動いてるのがubuntuなのでubuntuだと死ぬ？

**Comment by 2da-tuba** [comment]
僕のforkしたレポジトリのGitHub Actionsは正常でしたよ？
もう一度テストし直してみては？

**Comment by 2da-tuba** [comment]
あと手元のubuntu(wsl)はちゃんと動きました。

**Comment by RussianBlue25** [comment]
何か悪かったんですかね。とりあえず放置しときます。

**Comment by RussianBlue25** [comment]
ちなみにREADME.mdをupdateしたときにこけたので何か破壊的変更をしたわけではないです。

**Comment by 2da-tuba** [comment]
あ、if文の中で`date`を使っているのが悪いのかも...
秒がずれたらそれだけで判定がfalseになる

**Comment by 2da-tuba** [comment]
ちょっとそれ直します

**Comment by 2da-tuba** [comment]
#14 で直ったと思います

**Comment by RussianBlue25** [comment]
直ったようなのでcloseします
