### ISSUE TITLE
同一日付でkatコマンドを実行した際区別が行われない

### ISSUE THREAD

**Issue by imaizumi65** [RussianBlue25/kat#8]
kat afoにより
　afo　→　afo(2021年01月21日版)
なのであれば，その状態からのkat afoで
　afo(2021年01月21日版)　→　afo(2021年01月21日版)-2
など，その日の何番目のバックアップなのかをわかるようにしたい。
この際，afo(2021年01月21日版)そafo(2021年01月21日版)-1にするかどうかは要検討

**Comment by RussianBlue25** [comment]
多分時刻まで含めてしまうのが一番改修コストが少ない気がしますね。

**Comment by 2da-tuba** [comment]
#11 で対応しました

**Comment by RussianBlue25** [comment]
閉じます
