### ISSUE TITLE
ファイルのタイムスタンプが保存されない

### ISSUE THREAD

**Issue by imaizumi65** [RussianBlue25/kat#9]
バックアップ作成時にcpコマンドを使っているが，この方法ではタイムスタンプが作成時になってしまい，すでにファイル名に入っているものとダブってしまう。
一旦mvして，それを元の名前にcpすることにより，バックアップ側に現在のファイルのタイムスタンプが残るようになる。

**Comment by 2da-tuba** [comment]
タイムスタンプを保持したままにしたい場合は`cp -p`でできると思う（UnixとLinuxで挙動が違うかも？）ので、その機能をオプションでつけるのはどうでしょう?

**Comment by imaizumi65** [comment]
ファイルがハードリンクされていた場合にどうなるか考えてみましょう。Aにハードリンクがある時にBを作る。この時もともとAにハードリンクを張っていたものはAに張り続けた方が良いですね。そうすると，cp -rでも十分な気がしてきました。タイムスタンプにこだわるのは，makeで育ってきた名残。

**Comment by imaizumi65** [comment]
`cp -r`でするので良いが，それをデフォルトにしてしまってはどうか。-rオプションを付けない方が都合が良いという面が見当たらないのだが

**Comment by 2da-tuba** [comment]
解釈合ってるかわからないんですけど、
- A(ファイル)
- A*(Aへのハードリンク)
- A(x年x月x日版)  (kat Aでできたファイル)

が存在するとき、A\*はAを指し示していて欲しいということですか？
それともA\*はkatでできたファイルを指し示していて欲しいってことですか？

**Comment by 2da-tuba** [comment]
まぁそれとは別にディレクトリに対して`kat`をしたい場合にも`-r`は必要なのでデフォルトでつけても良いと思います。

**Comment by imaizumi65** [comment]
ハードリンクの話では，katで作ったファイルがBです。katコマンドをバックアップコマンドだと解釈するなら，ほかからさしているものは最新版を指した方が良いだろうということで，Aのinodeが変わらない方が良いかなと思いました。オプションでこれを逆にする（他からさしているものもバックアップ側を指す）オプションがあってもよいとは思います。ただ，これはハードリンクを使った時なので，普通のシンボリックリンクだとファイル名で見るのであまり意味がない。
